### ISSUE TITLE
www.20minutes.fr

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#165] opened 2021-06-20 14:07 UTC
Why is this website blocked? It is an official and legit French media.

**Comment by badmojr** [comment] 2021-06-21 03:10
Caused by a CNAME block, i.e **spiral.20mn.io**, originating from https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.txt; maintained by @blokadaorg .

Be fixed ASAP.

**Comment by badmojr** [comment] 2021-06-21 03:28
Fixed in https://github.com/badmojr/1Hosts/commit/de51c8e489c7c1db77e4e1a117511ab97dd19eb4 .

**Closed by badmojr** 2021-06-21 03:28 UTC

**Comment by Quorum75** [comment] 2021-06-22 21:06
Thx
