### ISSUE TITLE
1Hosts Xtra Blocking Issue

### ISSUE THREAD

**Issue by Quorum75** [badmojr/1Hosts#170] opened 2021-06-22 21:20 UTC
New user of 1Hosts Xtra great job by the way I don't understand why:

- So many legit domains are blocked. 
- But analytics (ex. sb.scorecardresearch.com) or ads (ex. r.teads.tv) are not blocked. 
I have to use Stevenblack host to blocked those. 

Thanks

**Comment by badmojr** [comment] 2021-06-23 04:03
Hello!
Xtra is a relatively new addition to the 1Hosts filter-/blocklists family.
Here's a preview of for whom it's designed/made.

![quickstart](https://user-images.githubusercontent.com/40524316/123032413-92975300-d3ee-11eb-978e-ef5c2ce02555.PNG)

As shown above, the recommended version is **1Hosts (Lite)**; which also blocks the domains mentioned above i.e sb.scorecardresearch.com & r.teads.tv .

They are likely not blocked by **mini** because that's a much toned-down & most lenient version on the set.
It designed for specific users; such as those who hate AdBlock detections, like to earn app rewards through watching ads, etc.

**Comment by Quorum75** [comment] 2021-06-23 08:46
I read your guide, however I thought that "Xtra" was a consolidation of all others. The same way it works with Stevenblack Hosts. 
From my angle it does not make sense that Lite version blocks analytics and not Xtra. 

Also, Xtra block many, many legit websites. 
I have hard time to read the morning news because of all the blockings. 

For instance today I had to white list:
- www.euronews.com
- www.shrm.org
- www.retaildive.com
- www.dealstreetasia.com
- www.arounddeal.com
- muckrack.com

I can't even read LinkedIn properly without being consistently blocked.

**Comment by badmojr** [comment] 2021-06-23 08:58
Hey again.
1Hosts (Xtra) is a level 4 version which means it blocks more ads, analytics, and trackers than mini, Lite, and Pro.
If it does not work as intended, then there may be s/th broken with your setup.

I am aware it blocks lots of legit sites hence the usage steps outline on the quickstart guide.
The above domains all false positives & will be removed ASAP. Thanks!

**Comment by Quorum75** [comment] 2021-06-23 09:03
"If it does not work as intended, then there may be s/th broken with your setup."

My setup is easy as I just added Xtra to Adguard. Not rocket science here ;)

Then, I just have to check AG log to see what it is blocked and allowed. 

I don't know if you want to unblock these domains, but here the screen shot of my Allow list that Xtra is blocking. 

 ![image](https://user-images.githubusercontent.com/49731083/123068856-91781d00-d412-11eb-998d-4e9365e2ebfb.png)

![image](https://user-images.githubusercontent.com/49731083/123068872-94730d80-d412-11eb-910b-48462998cb99.png)

**Comment by badmojr** [comment] 2021-06-23 09:08
Well, let's see some screenshots of the setup.

**Comment by Quorum75** [comment] 2021-06-23 09:16
What do you mean? 
Don't you know Adguard and how it works?
You just have to add your URL and that's it. I am using it since years now. 
![image](https://user-images.githubusercontent.com/49731083/123070938-7d351f80-d414-11eb-99d8-92803efa9612.png)

**Comment by badmojr** [comment] 2021-06-23 09:23
Go one step back & screenshot please.

**Comment by badmojr** [comment] 2021-06-23 09:39
BTW,
Just so we are on the same page that's iOS, right?
'Coz last time I checked, it had a limit on the umber of rules permitted.
It more a limitation of the OS than of the blocklist.

**Comment by Quorum75** [comment] 2021-06-23 09:50
Yes it AG Pro. 

However don't mix the 50K max rules for Safari and the 550K for DNS. 

Whenever you go over the number of rules allowed AG gives you a warning. In my case I am still under the maximum number of rules. 

Anyway, the activity log is here to help users to check what is blocked and allowed.

**Comment by badmojr** [comment] 2021-06-23 10:48
I have really run out of ideas on how to help you. The Xtra list currently has these blocked on my AdGuardHome setup.
![blocklist](https://user-images.githubusercontent.com/40524316/123083315-9c3dac80-d428-11eb-9155-b4ebfbf1eb28.PNG)


![app-m_crashlytics](https://user-images.githubusercontent.com/40524316/123083353-a3fd5100-d428-11eb-99c1-18e85658bf24.PNG)
![scorecardresearch](https://user-images.githubusercontent.com/40524316/123083373-a95a9b80-d428-11eb-9483-022bc2f0e774.PNG)
![teads](https://user-images.githubusercontent.com/40524316/123083392-aeb7e600-d428-11eb-9989-3c4c63054e4f.PNG)

The only domain not blocked is `device-api.urbanairship.com` & its parent which were reported to be used for notifications and have since then been removed from all versions of the lists.

**Comment by Quorum75** [comment] 2021-06-23 12:06
I understand, no worries. 
To be honest I don't how AG manages the different lists with the DNS filtering in term prioties. Meaning which filters will block first a domain. 

I just disabled all filters except yours. True everything is blocked. So why StevenBlack gets priority o' yours, I don't know. 

Regarding device-api.urbanairship.com I don't agree. 
First of all I never had any issue with notifications. 
Second of all in my opinion it has to be blocked for privacy reasons. You should know that Urban Airship provides several API endpoints that allow for retrieval of device identifiers and information associated with those devices. Something you don't want in order to not be tracked by apps. 

FYI Urban Airship Documentation on Device Listing API:
[https://docs.airship.com/api/ua/#device-token-listing](https://docs.airship.com/api/ua/#device-token-listing)

By the way, will you or not white list the domains from the screen shots I sent you, because there are all legits.

**Comment by badmojr** [comment] 2021-06-23 12:52
Glad to know you've found the source of the problem.

Currently, Urban Airship endpoints below are blocked.
```
web-sdk.urbanairship.com
go.urbanairship.com
wallet-api.urbanairship.com
sbux-dl.urbanairship.com
reach-api.urbanairship.com
web-push-api.urbanairship.com
```

& these are unblocked.
```
remote-data.urbanairship.com
device-api.urbanairship.com
```

The application in question that relies upon the domains above is allegedly FotMob.
Since you raised an objection to it, I will re-block them.

I am also working on getting the reported false positives fixed ASAP.

**Comment by badmojr** [comment] 2021-06-23 15:12
Hey,
Regarding your AG pro quagmire, try using  1Hosts( Pro): domain variant.
I got a feeling it might work.

Link: https://badmojr.github.io/1Hosts/Pro/domains.txt

**Comment by badmojr** [comment] 2021-06-23 15:27
Update https://github.com/badmojr/1Hosts/commit/5362adbe752b6f11b3ba094c4682371a05c68978 re-blocks the Urban Airship endpoints.

**Comment by Quorum75** [comment] 2021-06-23 20:43
Done. I removed Xtra and added Pro hosts.

**Comment by badmojr** [comment] 2021-06-24 05:27
Good call.
Closing..

**Closed by badmojr** 2021-06-24 05:27 UTC
